[package]
name = "tri-mesh"
version = "0.4.0" # REMEMBER TO UPDATE VERSION IN README!!
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"
description = "A triangle mesh data structure including basic operations."
license = "MIT"
readme = "README.md"
repository = "https://github.com/asny/tri-mesh"
categories = ["data-structures", "algorithms"]
keywords = ["mesh", "geometry", "3d", "half-edge", "graphics"]

[dependencies]
cgmath = "0.16.1"
wavefront_obj = "5.1.0"

[dev-dependencies]
dust = {path = "examples/dust/", version = "0.1.0"}