[package]
name = "tri-mesh"
version = "0.1.2" # REMEMBER TO UPDATE VERSION IN README!!
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"
description = "A triangle mesh data structure including basic operations."
license = "MIT"
readme = "README.md"
repository = "https://github.com/asny/tri-mesh"
categories = ["data-structures", "algorithms"]
keywords = ["mesh", "geometry", "3d", "half-edge", "graphics"]

[dependencies]
cgmath = "0.16.1"

[dev-dependencies]
dust = {git = "https://github.com/asny/Dust"}
geo-proc = {git = "https://github.com/asny/geo-proc"}